### ISSUE TITLE
does not compile with ghc-8.8 (Could not deduce (MonadFail m) arising from a use of ‘fail’)

### ISSUE THREAD

**Issue by jwaldmann** [mfourne/prolog#3]
when I pull from hackage, I get the following. Perhaps this is already fixed in the repo? Please make a release, then.

```
rolog                          > Preprocessing library for prolog-0.3..
prolog                          > Building library for prolog-0.3..
prolog                          > [ 1 of 11] Compiling Syntax
prolog                          > [ 2 of 11] Compiling Parser
prolog                          > [ 3 of 11] Compiling Database
prolog                          > [ 4 of 11] Compiling Unifier
prolog                          > 
prolog                          > /tmp/stack-fb5ff986ac7dc753/prolog-0.3/src/Unifier.hs:25:33: error:
prolog                          >     • Could not deduce (MonadFail m) arising from a use of ‘fail’
prolog                          >       from the context: MonadPlus m
prolog                          >         bound by the type signature for:
prolog                          >                    unify_with_occurs_check :: forall (m :: * -> *).
prolog                          >                                               MonadPlus m =>
prolog                          >                                               Term -> Term -> m Unifier
prolog                          >         at src/Unifier.hs:19:1-74
```

**Comment by mfourne** [comment]
prolog-0.3.1 should be on hackage now, only small changes from the former repo state and test compiled with GHC8.8.4. If this does not fix your issue, please don't hesitate to get in contact.
